### ISSUE TITLE
Create Sections personal-info, details and browsing-mode

### ISSUE THREAD

**Issue by tahminarasoli** [rago89/DuckDuckGoGroup6#2]
-[X] Fork repo
- [X] Create an issue in the repo, add the labels and project label
- [ ] Create a branch `personal-info`
- [X] Create a index.html file
- [X] Create a style.css file
   - Work with @media Query to make the web responsive
- [X] Create a link in the index.html to ref style.css
- [ ] Work in the section `personal-info` according to the wireframe and the website [duckduckgo](https://duckduckgo.com/?va=z&t=hr&atb=v214-1)
- [ ] Change your status in the project, to follow the work
- [ ]Repeat the precedent steps except the first to the section `details` and `browsing-mode`

**Comment by rago89** [comment]
Hi Tahmina I'm seen in the first and the last task of your issue is wrong the checklist's markdown

**Comment by tahminarasoli** [comment]
> Hi Tahmina I'm seen in the first and the last task of your issue is wrong the checklist's markdown

Updated accordingly, thanks.
