### ISSUE TITLE
Create Section dockmain

### ISSUE THREAD

**Issue by preeti-t** [rago89/DuckDuckGoGroup6#3]
- [x] Fork repo DuckDuckGoGroup6
- [x]  Create an issue in the repo, add the labels and project label
- [x]  Create a branch named dockmain
- [x]  Create a index.html file
- [x]  Create a style.css file
        Work with @media Query to make the web responsive
- [x] Create a link in the index.html to ref style.css
- [x] Work in the section dockmain according to the wireframe and the website duckduckgo
- [x] Change your status in the project, to follow the work

**Comment by rago89** [comment]
Is not done the task in the issue, I'll reopen it.
